### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;

### ISSUE THREAD

**Issue by jakal23** [data2viz/data2viz#258]
at kotlinx.datetime.Instant.<clinit>(Instant.kt:78)
       at kotlinx.datetime.Clock$System.now(Clock.kt:17)
       at io.data2viz.charts.logging.LoggingKt.<clinit>(Logging.kt:21)
       at io.data2viz.charts.logging.LoggingKt.access$timeInfo(Logging.kt:1)
       at io.data2viz.charts.logging.KLogger.verbose$core_release(Logging.kt:45)
       at io.data2viz.charts.chart.internal.ChartImpl.<init>(ChartImpl.kt:563)
       at io.data2viz.charts.chart.ChartKt.chart(Chart.kt:39)
       at com.atcc.drivingtests.app.view.RankChart.applyChart(RankChart.kt:39)
       at com.atcc.drivingtests.app.view.RankChart.<init>(RankChart.kt:28)
       at com.atcc.drivingtests.ui.rank.RankFragment.onCreateView(RankFragment.kt:24)
       
       Caused by java.lang.ClassNotFoundException: Didn't find class "java.time.Instant" on path: DexPathList[[zip file "/data/app/com.atcc.drivingtests-1/base.apk", zip file "/data/app/com.atcc.drivingtests-1/split_config.armeabi_v7a.apk", zip file "/data/app/com.atcc.drivingtests-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.atcc.drivingtests-1/lib/arm, /data/app/com.atcc.drivingtests-1/base.apk!/lib/armeabi-v7a, /data/app/com.atcc.drivingtests-1/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.atcc.drivingtests-1/split_config.xxhdpi.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

Device Galaxy J7, Android 7

**Comment by LouisCAD** [comment]
Hello, this is an issue in Charts.kt, not in Data2Viz. Can you send the issue in the Charts.kt-samplea repository, and just for reference, write down which Charts.kt version you're using?

We can fix this issue next week.

Thank you and have a great day!

**Comment by LouisCAD** [comment]
Tracking in Charts.kt-samples, since this is not a data2viz issue.
